### PR TITLE
Emojify

### PR DESCRIPTION
**Pull request by gboone**
Adds support for emoji in the hub! Now you can :scream: :thumbsup: or :heart_eyes_cat: all your hub pages. 💪💻🇺🇸

### CODE REVIEW

**Comment by mbland** [comment]
Can't believe I'm actually merging this... :stuck_out_tongue_closed_eyes:

**Comment by afeld** [comment]
Should have mentioned that I had a solution for this :-)

http://afeld.github.io/emoji-css/

**Comment by mbland** [comment]
I can haz PR, @afeld?

**Comment by afeld** [comment]
*Meh*, not worth fixing since it isn't broken.

**Pull request merged**
