### PR TITLE
Next-gen nav and structure

### PR DESCRIPTION
**Pull request by meiqimichelle**
This PR restructures the nav on our beloved hub based on discussions over the last few weeks in wg-documentation on information architecture and priority tasks for our group.

Right now, it looks like this:
screenshot 2015-01-21 20 42 09

There is a 'landing page' for each nav item that can be filled with the content that we talked about and that is represented in virtual post-it notes on our murally board.

~~I'm leaving the PR open because before we start filling in content, I'll like to work through some of the site front-end coding with @mbland . I ran into a problem around `_layouts` acting like `pages`, and changes in `_layouts` breaking the site build.~~ Issue addressed.

Also, I didn't add any responsive code to this version (so, the old responsive work will carry forward, but any new stuff, ie, the new nav, will not look good on anything but desktop). Team, let me know if you'd like this addressed before merge.

### CODE REVIEW

**Comment by mbland** [comment]
:heart:

@meiqimichelle thanks again for taking this on; I'm ready to help figure out the the `_layouts` issue whenever you have the time.

**Comment by mbland** [comment]
I pulled this down to my local repo and got it running...whee! :-) Really love how this is starting to look. Couple of thoughts:

- Should we post snippets as part of the top-level nav? (Seems like it'd make it a bit crowded.) Or should we incorporate them into the "Team" page somehow?
- By the same token, we may need an "Internal Info" tab or some such, as a portal to the stuff in `/pages/private`.
- Would a drop-down nav scheme be advisable to accommodate some of this extra stuff?

And something I need to figure out: When serving locally via `./go serve`, the nav bar looks exactly like your screenshot. When I run `./go build`, `vagrant up`, and look at 'localhost:8080' (to more closely emulate our production `nginx` setup), I see this:

pr-73-next-gen-nav

**Comment by meiqimichelle** [comment]
There is still no responsive code in this new work, but I think it is more valuable to merge now rather than wait for the better code, and get feedback from our 18F team on our direction. The big job here was cleaning up docs and migrating information from across our organization to one place.

**Comment by meiqimichelle** [comment]
This closes #48 and #41.

**Comment by mbland** [comment]
OK, just pulled, rebased, and `push -f`'d. @meiqimichelle take a look, and merge if it looks good to you!

**Comment by meiqimichelle** [comment]
Tested public and private versions locally, LGTM :ship:

**Pull request merged**
