### PR TITLE
Use weekly_snippets gem

### PR DESCRIPTION
**Pull request by mbland**
@afeld @adelevie Another step towards extracting reusable components from the Hub!

### CODE REVIEW

**Comment by mbland** [comment]
Note that this PR (geez, I actually just reflexively typed "CL") fails on Travis because #33 isn't merged yet.

**Comment by afeld** [comment]
Once the build here passes, :ship:

**Comment by mbland** [comment]
Hey @afeld, care to merge? (Or when you say "once the build here passes" is that a free pass for me to merge it myself?)

**Comment by afeld** [comment]
Yep, that's what I meant. Whateva!

**Pull request merged**
