### PR TITLE
fix broken links

### PR DESCRIPTION
**Pull request by afeld**
See commits.

### CODE REVIEW

**Comment by mbland** [comment]
Looks like Travis is bummed...

**Comment by afeld** [comment]
I think the tests are failing on Travis but not locally (on Mac) because of the case-sensitive filesystem :rage: Will investigate in a few hours, unless you have a moment to look at it sooner?

**Comment by mbland** [comment]
Wish I did, but if you don't get to it by the next time I look, I'll look as well. (Wonder if Travis has a case-insensitive FS setting?)

**Comment by afeld** [comment]
Phew, ok, fixed by canonicalizing (downcasing) the user `name`s across the various templates. :boom:

**Pull request merged**
