### PR TITLE
Add Working Groups nav bar item

### PR DESCRIPTION
**Pull request by mbland**
@meiqimichelle: Folks have been asking more frequently "How many working groups are there and what are they?" Happy to entertain a different means of surfacing them, but here's my stab.
2015-03-19-hub-wg

### CODE REVIEW

**Comment by meiqimichelle** [comment]
I'm not sure of the best solution yet, but I'd like to wait to make changes until we have a designer (and/or anyone who has time to volunteer) (maybe a fixit task for the new folks?) take a look at the site nav again overall. For example, if we make a top-level nav item for Working Groups, then my next question is...."but where are the Guilds?" and I don't want to go down the path of making All The Things top-level links.

Is there an issue for this, erm, issue? ;)

**Comment by mbland** [comment]
`/wg/` contains both working groups and guilds. In the short-term, I'd prefer to have some kind of link to that page, even if there's a better way to do it later. Right now, it's not directly accessible from anywhere.

Would you prefer to file a site-nav issue? I can do it, but I doubt I'd be able to express the concerns as well as you. ;-)

And yes, it indeed might make a great fixit task!

**Comment by meiqimichelle** [comment]
Right now, working groups and guilds are under "18F Stucture", right? That is how they're accessible?

**Comment by meiqimichelle** [comment]
Also, I added some detail to #213 to address the site nav. It was on my mind when I wrote that issue.

**Comment by mbland** [comment]
OK, I totally missed the "18F Structure" listing... Maybe that'll do. But yes, we probably do need to have some kind of site-structure pow-wow next week.

**Pull request closed without merging**
