### PR TITLE
Update gsa-approved-software.md

### PR DESCRIPTION
**Pull request by andrewmaier**
cc @afeld @mbland

### CODE REVIEW

**Comment by andrewmaier** [comment]
Can someone tell me who asks for this information? Not sure why it's on the Hub to begin with.

**Comment by afeld** [comment]
Methinks this doesn't apply since we aren't using the centrally-managed software that the GSA PCs would...maybe can just get rid of the page altogether, in favor of

https://github.com/18F/hub/blob/master/_pages/qa/request-supplies.md

/cc @kimberbat

**Comment by andrewmaier** [comment]
Per conversation with @kimberbat (https://18f.slack.com/archives/equipment/p1447436553000006) I'm deleting this page.

**Comment by kimberbat** [comment]
Deleted in favor of https://github.com/18F/hub/blob/master/_pages/qa/request-supplies.md

**Pull request merged**
