### PR TITLE
Give Coveralls.io a spin

### PR DESCRIPTION
**Pull request by mbland**
@arowla Let's see if this is all it takes to get Coveralls working.

### CODE REVIEW

**Comment by mbland** [comment]
D'oh! Forgot to add my `Gemfile.lock`. Fixed now.

**Comment by mbland** [comment]
@arowla Seems to be good to go now: https://coveralls.io/builds/2192757

Mind merging?

**Comment by afeld** [comment]
Sorry for not saying something earlier, but not sure that we need Coveralls _and_ Code Climate...

http://docs.codeclimate.com/article/219-setting-up-test-coverage

**Comment by arowla** [comment]
Yep. We were just testing out Coveralls in relation to some stuff the Testing Grouplet is doing, since Code Climate does not support Python.

**Pull request merged**
