### PR TITLE
Disable Jekyll 3 .jekyll-metadata cache for now

### PR DESCRIPTION
**Pull request by mbland**
See #209. cc: @afeld

### CODE REVIEW

**Comment by afeld** [comment]
We should try reverting this now that #457 is in.

**Comment by mbland** [comment]
I did. No impact.

**Comment by afeld** [comment]
Meaning the bug is still present?

**Comment by mbland** [comment]
Ah, I just noticed looking more closely at the output from yesterday, that you have to set `incremental:` in `_config.yml` or pass the `--incremental` flag to enable it. Previously, I'd defined `full_rebuild: true` in `_config.yml` to disable it, so commenting out that line didn't actually have an effect.

Running it correctly now, the `.jekyll-metadata` file is now in a binary format. It doesn't appear to change its size when touching the same file repeatedly, but it does change a little when touching different files. It doesn't appear to have the same bug that eventually caused it to crash, though.

So it seems to work. It seems to shave off a little bit of time, if not a ton, probably because so many pages are generated via plugins and thus probably can't be incrementally regenerated. I'll send a PR.

--------------------------------

Here's a run where I just kept touching files over and over:

```
$ ./go serve --incremental
Configuration file: src/18F/hub/_config.yml
            Source: src/18F/hub
       Destination: src/18F/hub/_site
 Incremental build: enabled
      Generating... 
                    done in 9.653 seconds.
 Auto-regeneration: enabled for 'src/18F/hub'
Configuration file: src/18F/hub/_config.yml
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
      Regenerating: 1 file(s) changed at 2015-10-28 09:11:08 ...done in 9.108171 seconds.
      Regenerating: 1 file(s) changed at 2015-10-28 09:11:20 ...done in 8.837934 seconds.
      Regenerating: 1 file(s) changed at 2015-10-28 09:11:38 ...done in 8.592914 seconds.
      Regenerating: 1 file(s) changed at 2015-10-28 09:12:33 ...done in 8.707167 seconds.
      Regenerating: 1 file(s) changed at 2015-10-28 09:13:35 ...done in 8.740737 seconds.
      Regenerating: 1 file(s) changed at 2015-10-28 09:15:50 ...done in 8.748956 seconds.
      Regenerating: 1 file(s) changed at 2015-10-28 09:17:00 ...done in 8.475603 seconds.
      Regenerating: 1 file(s) changed at 2015-10-28 09:17:14 ...done in 9.016803 seconds.
```

Here's a run where I started a new incremental build after the previous one and touched a file:

```
$ ./go serve --incremental
Configuration file: src/18F/hub/_config.yml
            Source: src/18F/hub
       Destination: src/18F/hub/_site
 Incremental build: enabled
      Generating... 
                    done in 8.265 seconds.
 Auto-regeneration: enabled for 'src/18F/hub'
Configuration file: src/18F/hub/_config.yml
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
      Regenerating: 1 file(s) changed at 2015-10-28 09:18:45 ...done in 8.938677 seconds.
```

And here's a run where I did a regular non-incremental build and touched a file twice:

```
$ ./go serve 
Configuration file: src/18F/hub/_config.yml
            Source: src/18F/hub
       Destination: src/18F/hub/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 9.613 seconds.
 Auto-regeneration: enabled for 'src/18F/hub'
Configuration file: src/18F/hub/_config.yml
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
      Regenerating: 1 file(s) changed at 2015-10-28 09:19:36 ...done in 12.725442 seconds.
      Regenerating: 1 file(s) changed at 2015-10-28 09:19:58 ...done in 13.08852 seconds.
```

**Pull request merged**
