### PR TITLE
Update onboarding.md

### PR DESCRIPTION
**Pull request by thecapacity**
Added suggested activities (updating Hub Profile) and Git Team Group

### CODE REVIEW

**Comment by mbland** [comment]
LGTM, but I'd like to get @wslack's thumbs-up regarding the course materials. Will may prefer to point to https://pages.18f.gov/slides/github-basics/#/.

**Comment by thecapacity** [comment]
Yea, I wasn't sure but wanted to particularly mention that there might be "team specific" groups to be added to, but w/o more thorough knowledge I'm not sure it should be an explicit step.

This post too might be a good Git reference: https://18f.gsa.gov/2015/03/03/how-to-use-github-and-the-terminal-a-guide/

**Comment by thecapacity** [comment]
Hmm, I didn't mean to close the request - not sure how to comment on it w/o that happening?

**Comment by wslack** [comment]
We should reference the pages site as a slide presentation with walkthrough exercises, the google doc as a long-form written guide to github basics, and mel and Greg's post as a command line + GitHub guide+walkthrough.

Let people decide what they need.

Also my course will be youtube'd at some point and people can watch it who are utter github newbies.

**Comment by wslack** [comment]
suggest closing this given transition of onboarding @thecapacity and @mbland

**Pull request closed without merging**
