### PR TITLE
clarify that PIFs should be added to Slack

### PR DESCRIPTION
**Pull request by afeld**
Per https://18f.slack.com/archives/admins-slack/p1443648124000836.

/cc @quepol

### CODE REVIEW

**Comment by wslack** [comment]
Hmmm. do we want to say its required for PIFs @afeld or that they have access as full members as needed?

**Comment by afeld** [comment]
That seems like a @FreeMason question – no strong feelings from my end.

**Comment by afeld** [comment]
...but I would say that we should default to including them.

**Comment by afeld** [comment]
Ok, got a :+1: from Puja and @rossdakin. Merging!

**Comment by stroupaloop** [comment]
Confirming on here, all PIF should be added to 18F Slack by default. Thanks!

**Pull request merged**
