### PR TITLE
Approximate Jen Thibault's Hub index page concept

### PR DESCRIPTION
**Pull request by mbland**
Here's @jenniferthibault's original concept:

hub landing private-v1

Here's my current approximation, implemented in this PR (minus the login image):

hub-redesign

@meiqimichelle and @shawnbot: Care to help me whip this into shape?

### CODE REVIEW

**Comment by meiqimichelle** [comment]
I don't have time :( Love the concept tho! Woooo @jenniferthibault !!

**Comment by mbland** [comment]
@shawnbot I may take you up on your pairing/code review offer. In the short term, does this look good enough to merge to you? (And feel free to hit the button.)

**Comment by afomi** [comment]
Thanks for working in the open!

https://github.com/18F/hub/pull/294

**Comment by mbland** [comment]
So here's where we are now after I merged the master back into this branch after @afomi's #294 and pushed a couple fixup commits:

post-atomi

@afeld, @meiqimichelle or @jenniferthibault, would any of y'all care to merge?

**Comment by afeld** [comment]
:rocket:

**Pull request merged**
