### PR TITLE
Change Greg Godbout to Greg Boone

### PR DESCRIPTION
**Pull request by awfrancisco**

### CODE REVIEW

**Comment by afeld** [comment]
@gboone Why didn't you *tell* us you were formerly Greg Godbout???

**Comment by gboone** [comment]
Shhhh! There's a reason we were never in the same room.

**Comment by wslack** [comment]
This is my favorite PR title. :D

**Comment by mbland** [comment]
FYI, we may be down to one Greg, but we've now got two Diegos.

**Pull request merged**
