### PR TITLE
cross_referencer tests and refactoring

### PR DESCRIPTION
**Pull request by mbland**
The `CrossReferencerImpl` is now completely covered by tests, and I made some improvements to boot. Once this goes in, I'll extract these bits into [team_hub](https://github.com/18F/team_hub).

cc: @afeld

### CODE REVIEW

**Comment by afeld** [comment]
My overall feedback is that it would be nice to not need all of the `|| []` everywhere... maybe something like this in the initialization, so you only need to do it once?

```ruby
site_data['snippets'] ||= []
```

**Comment by mbland** [comment]
I'll give that a go and ping again when ready.

**Comment by mbland** [comment]
Hey @afeld, I haven't updated this yet, but I should've mentioned: I originally left things `nil` so that the Liquid templates could check (for example) `{% if member.working_groups %}` before deciding whether or not to render the "Working Groups" section of the page, versus `{% if member.working_groups.size != 0 %}` or rendering the "Working Groups" headline without any actual content.

Hence, a question: Keep things as-is, or add a filtering pass to remove empty Arrays and Hashes from all objects after Joining/Cross-referencing? (Might be something to add to `hash-joiner`, a recursive attribute pruner.)

**Comment by afeld** [comment]
Gotcha. No strong feelings!

**Comment by mbland** [comment]
Cool. Then do you mind merging as-is? Then I can yank this code into [`team_hub`](https://github.com/18F/team_hub) and revisit the decision there.

**Comment by mbland** [comment]
Starting to address this in 18F/hash-joiner#7.

**Pull request merged**
