### PR TITLE
Delete gsa-dell.md

### PR DESCRIPTION
**Pull request by andrewmaier**
This self-service documentation feels superfluous given that we don't issue Dells to new hires.

### CODE REVIEW

**Comment by andrewmaier** [comment]
cc @mbland @NoahKunin @afeld

**Comment by afeld** [comment]
> we don't issue Dells to new hires

Is that true? I'm pretty sure I got one, and @lsgitter locked it in a drawer.

**Comment by andrewmaier** [comment]
Still not sure you need this content @afeld :)

**Comment by afeld** [comment]
Agreed :+1:

**Pull request merged**
