### PR TITLE
Added a link to Tock FAQ

### PR DESCRIPTION
**Pull request by StephaniePlageman**

### CODE REVIEW

**Comment by wslack** [comment]
Hey @afeld, what is policy with Google Doc links like this on a public page? (if this is a public page?)

**Comment by afeld** [comment]
It's not a _huge_ deal since the access is controlled separately, but we should [figure out a better way to handle them](https://github.com/18F/hub/issues/413).

**Comment by afeld** [comment]
p.s. thanks @StephaniePlageman!

**Comment by mbland** [comment]
Sorry I didn't catch this sooner, but ["click here"-style links aren't very accessible](https://pages.18f.gov/accessibility/links/). We also [prefer active voice to passive](https://pages.18f.gov/content-guide/active-voice/).

Since I'm on vacation, I'll resist the urge to update this myself, but something like this may be better:

```
Learn more about Tock from the [Tock FAQ](...).
```

**Comment by wslack** [comment]
@StephaniePlageman

**Pull request merged**
