### PR TITLE
Use prose.io as the default pages/ editor

### PR DESCRIPTION
**Pull request by mbland**
It's aliiiive! Let's play around with this and see how we like it, and how we can improve prose.io!

cc: @dhcole @meiqimichelle @gboone @elainekamlley @afeld

### CODE REVIEW

**Comment by meiqimichelle** [comment]
Ooooooo yeeeeaaaahhh

**Comment by dhcole** [comment]
Looks good. One option to cut down on a server would be to check out prose into `/edit` of this repo.

**Comment by mbland** [comment]
@dhcole Hmm... as a submodule, maybe? Let me sleep on it...others welcome to weigh in too, of course!

**Comment by dhcole** [comment]
Sub module or just `git clone ... prose`. Nice to see this working though!

**Pull request merged**
