### PR TITLE
Enable automated deployment

### PR DESCRIPTION
**Pull request by mbland**
@gboone @konklone I think I've got this working for the "staging-public" instance, with a webhook pointed at https://18f.gsa.gov/hub/deploy. Guess I won't know for sure until I merge something into the staging-public branch, unless y'all know of a way to test it ahead of time.

Also, there's a potential issue setting up automated deployment for production-public on 18f.gsa.gov, as I mentioned in #36.

BTW, the `set $authenticated_user $http_x_forwarded_email;` directive should've gone in a while back; I must've missed it as part of 4bdd9bf25106235fc46ba52ea9c23dba3cd3a056 from #3.

### CODE REVIEW

**Comment by gboone** [comment]
You could test it by pushing up something inconsequential, checking if it deployed and then pushing up another commit to roll it back. I'll comment on the other issue separately.

**Comment by konklone** [comment]
I'd do local testing of webhooks with [ngrok](http://ngrok.com/) (have GitHub post the hook to your laptop) - maybe you did that already. Yeah, for staging testing, I usually just commit whitespace to the README or an HTML comment to the template and watch it show up.

**Comment by mbland** [comment]
OK, just ran through this with @gboone for the staging-public branch (https://18f.gsa.gov/hub) by pushing a `.github-webhook-test-trigger` file, and all appears in-order there. I'll follow up with another PR for the production-public setup.

**Comment by mbland** [comment]
Heh, had to add one more commit; bundler wasn't being found and the site wasn't getting generated as a result. Now confirmed that https://18f.gsa.gov/hub is up via automated deployment.

**Comment by mbland** [comment]
@gboone Got this to pass Travis; care to merge?

**Comment by mbland** [comment]
Generated a public key so that the internal Hub user can update the private submodules, and managed to strip down the internal Hub deployments. Confirmed that the internal Hub and the public staging instance (on the same machine) are being rebuilt with each update to `master`.

@gboon: Care to merge?  I could also probably launch the `production-public` instance on 18f.gsa.gov itself, but I'd rather wait to get a few other PRs into `master` first.

**Comment by mbland** [comment]
Dig this: I got updates to [data-private](https://github.com/18F/data-private) and [hub-pages-private](https://github.com/18F/hub-pages-private) to automatically propagate to the [internal Hub](https://hub.18f.us) and [staging instance of the public Hub](https://hub.18f.us/hub/). Final proof: I added "18F Hub" as a specialty to [my profile](https://hub.18f.us/team/mbland/) ([public staging version](https://hub.18f.us/hub/team/mbland/)):
- `data-private` commit: 18F/data-private@a7ffd88f99bc790b08ea2522438ff1f64c48685c
- Hub commit: 18F/hub@56a8c8b47eadc77fff2284458acc050e9c3c9ab8

**Comment by gboone** [comment]
LGTM merging.

**Pull request merged**
